### ISSUE TITLE
Port Chrome Extension 

### ISSUE THREAD

**Issue by krruzic** [joaomgcd/JoinFirefox#2]
Why not just port the chrome extension like this: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

I've tried it already with [this](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/) and there are a few issues. Number one is it never asks you to sign in whatsoever. Number 2 is that some of the display stuff is garbled and messed up. I obviously cannot test any features like notifications because I can't sign in. But this is probably a lot easier route to go down then rewriting it. If you could maybe debug why the signin page never appears (at least when loading a temp extension) through this method I feel like you'd make a lot of progress.

I've never made an extension before so IDK. Just a random idea.

**Comment by joaomgcd** [comment]
Unfortunately the biggest issue is the most crucial one: Firefox doesn't support the GCM APIs which is the backbone of Join for receiving pushes.

**Comment by krruzic** [comment]
Ahh, didn't know how you were sending notifications from the app.
